import { Metadata } from "next";
import { getTodoDetail } from "../action";
import { ITodo } from "../type";

export const metadata: Metadata = {
  title: "Todo List Detail",
  description: "Generated by create next app",
};

export default async function Page({
  params,
}: {
  params: Promise<{ objectId: string }>;
}) {
  const objectId = (await params).objectId;
  const todo: ITodo = await getTodoDetail(objectId);
  return (
    <div>
      <h1>desc: {todo.desc}</h1>
      <h1>status: {todo.isChecked ? "Done" : "Process"}</h1>
    </div>
  );
}
